//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsSqlToolBelt.Data.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsSqlToolBelt.Data.Queries.QueryManager", typeof(QueryManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///    Author:        A. Pouwels
        ///    Changed by:    A. Pouwels
        ///    Creation date: 2020-06-22
        ///    Change date:   2021-01-27
        ///    Description:   Loads all available tables
        ///    Used by:       MsSqlToolBelt
        ///*/
        ///
        ///DECLARE @tables TABLE
        ///(
        ///    [Name] sysname NOT NULL,
        ///    [Schema] sysname NOT NULL
        ///);
        ///
        ///INSERT INTO @tables
        ///SELECT 
        ///    t.TABLE_NAME,
        ///    t.TABLE_SCHEMA
        ///FROM
        ///    INFORMATION_SCHEMA.TABLES AS t
        ///ORDER BY 
        ///    t.TABLE_NAME;
        ///
        ///-- Return the tables
        ///SELECT
        ///    t.[Name],
        ///    t.[Schema]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadTables {
            get {
                return ResourceManager.GetString("LoadTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///    Author:        A. Pouwels
        ///    Changed by:    A. Pouwels
        ///    Creation date: 2020-06-17
        ///    Change date:   2021-01-27
        ///    Description:   Loads all available table types
        ///*/
        ///
        ///-- Load all available table types
        ///SELECT 
        ///    tt.type_table_object_id AS Id,
        ///    tt.[name]
        ///FROM
        ///    sys.table_types AS tt
        ///WHERE
        ///    tt.is_user_defined = 1;
        ///
        ///-- Load the columns of the table types
        ///SELECT
        ///    tt.type_table_object_id AS TableTypeId,
        ///    c.[name] AS [Name],
        ///    st.[name] AS Datatype,
        ///    CASE
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadTableTypes {
            get {
                return ResourceManager.GetString("LoadTableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @result TABLE
        ///(
        ///    [Id] INT NOT NULL,
        ///    [Name] NVARCHAR(200) NOT NULL,
        ///    [Definition] NVARCHAR(MAX) NULL,
        ///    [Type] NVARCHAR(50) NOT NULL
        ///);
        ///
        ///INSERT INTO @result
        ///SELECT
        ///    m.object_id,
        ///    OBJECT_NAME(m.object_id) AS [Name],
        ///    m.[definition] AS [Definition],
        ///    CASE o.[type]
        ///        WHEN &apos;AF&apos; THEN &apos;Aggregate function&apos;
        ///        WHEN &apos;C&apos; THEN &apos;Check constraint&apos;
        ///        WHEN &apos;D&apos; THEN &apos;Default&apos;
        ///        WHEN &apos;F&apos; THEN &apos;Foreign key constraint&apos;
        ///        WHEN &apos;FN&apos; THEN &apos;Function&apos;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
    }
}
